plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# Permalinks
permalink: /:categories/:title/

# Setup
title: Prashant Kuntala
tagline: '@prashantkuntala'
description: ""
url: https://prashantkuntala.github.io
baseurl: /

paginate: 5

# Custom vars
github:
  repo: https://github.com/PrashantKuntala
linkedIn: https://linkedin.com/in/prashantkumarkuntala
twitter: https://twitter.com/prashkuntala
codepen: https://codepen.io/prashantkuntala
