plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-gist
  - jemoji

# Permalinks
permalink: pretty

# Setup
title: Musings in Ink
tagline: '@prashantkuntala'
description: "by Prashant Kuntala"
url: https://prashantkuntala.github.io
baseurl: /

paginate: 5

# Custom vars
github:
  repo: https://github.com/PrashantKuntala
linkedIn: https://linkedin.com/in/prashantkumarkuntala
twitter: https://twitter.com/prashkuntala
